server:
  port: 8991
spring:
  application:
    name: xdd-app
  profiles:
    active: test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/*/*.xml
  typeAliasesPackage: com.hznu.xdd.pojo.*DO

validCode:
  length: 8
  time: 300    # 5分钟


#微信公众号配置参数
wxOfficial:
  Token: 576ebfdfc96a2fa50c8cd5195308b5
  AppId: wxa9c8c5ecfa04d4c5
  EncodingAESKey: N90MioDJPTl1nhgwjNKc8Kyj3SaQ0qFhRMf67G4Tcpx
  APPSECRET: bd06722f270a50fef916b91729458eb2



